name: GetZone
main: net.yeticraft.squatingyeti.GetZone.GetZone
version: 1.2
description: >
             GetZone
commands:
  getzone:
    aliases: [gz]
    description: Gets the current zone of a player
    usage: /getzone